version: '3.7'
services:
  app_proxy:
    environment:
      APP_HOST: widgets-cwidgets_widget-server_1
      APP_PORT: 3000
    container_name: widgets-cwidgets_app_proxy_1
  widget-server:
    build:
      context: /home/umbrel/umbrel/app-data/widgets-cwidgets
    restart: on-failure
    container_name: widgets-cwidgets_widget-server_1
