version: '3.7'
services:
  app_proxy:
    environment:
      APP_HOST: widgets-clock-widget_widget-server_1
      APP_PORT: 3000
    container_name: widgets-clock-widget_app_proxy_1
  widget-server:
    image: yourdockerhubuser/widgets-clock-widget:1.0.0
    restart: on-failure
    container_name: widgets-clock-widget_widget-server_1
